
# Status Constants for the plant
STATUS_DIRT = 0
STATUS_SEED = 1
STATUS_SAPLING = 2
STATUS_PLANT = 4
STATUS_FULLGROWN = 7
STATUS_DECORATIVE = 10
STATUS_DEAD = 11

# Growth Stages
STATUS_STAGE1 = 1
STATUS_STAGE2 = 2
STATUS_STAGE3 = 3
STATUS_STAGE4 = 4
STATUS_STAGE5 = 5
STATUS_STAGE6 = 6
STATUS_STAGE7 = 7
STATUS_STAGE8 = 8
STATUS_STAGE9 = 9

# Growth Indicators
GROWTH_NONE = 0
GROWTH_INVALIDLOCATION = 1
GROWTH_NOTHEALTHY = 2
GROWTH_DELAY = 3
GROWTH_GROWN = 4
GROWTH_DOUBLEGROWN = 5

# Health Indicators
HEALTH_DYING = 3
HEALTH_WILTED = 2
HEALTH_HEALTHY = 1
HEALTH_VIBRANT = 0

# Modifier Flags
FLAG_CROSSABLE = 0x4000
FLAG_BRIGHT = 0x8000

# Plains
COLOR_NONE = 0
COLOR_PLAIN = 1

# Primaries
COLOR_RED = 2 | FLAG_CROSSABLE
COLOR_BLUE = 4 | FLAG_CROSSABLE
COLOR_YELLOW = 8 | FLAG_CROSSABLE

COLOR_BRIGHTRED = COLOR_RED | FLAG_BRIGHT
COLOR_BRIGHTBLUE = COLOR_BLUE | FLAG_BRIGHT
COLOR_BRIGHTYELLOW = COLOR_YELLOW | FLAG_BRIGHT

# Secondaries
COLOR_PURPLE = COLOR_RED | COLOR_BLUE
COLOR_GREEN = COLOR_BLUE | COLOR_YELLOW
COLOR_ORANGE = COLOR_RED | COLOR_YELLOW

COLOR_BRIGHTPURPLE = COLOR_PURPLE | FLAG_BRIGHT
COLOR_BRIGHTGREEN = COLOR_GREEN | FLAG_BRIGHT
COLOR_BRIGHTORANGE = COLOR_ORANGE | FLAG_BRIGHT

# Specials
COLOR_BLACK = 0x10
COLOR_WHITE = 0x20
COLOR_PINK = 0x40
COLOR_MAGENTA = 0x80
COLOR_AQUA = 0x100
COLOR_FIRERED = 0x200
