
from wolfpack.consts import *

ARMOR_RESNAME_BONI = {
	# Metals
	'iron': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0,
	},
	'dullcopper': {
		RESISTANCE_PHYSICAL: 6,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0,
		LOWERREQS: 20,
		MATERIALPREFIX: 'Dull Copper',
	},
	'shadowiron': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 5,
		MATERIALPREFIX: 'Shadow Iron',
	},
	'copper': {
		RESISTANCE_PHYSICAL: 1,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 2,
		MATERIALPREFIX: 'Copper',
	},
	'bronze': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 5,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 1,
		MATERIALPREFIX: 'Bronze',
	},
	'gold': {
		RESISTANCE_PHYSICAL: 1,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 2,
		LUCK: 40,
		LOWERREQS: 30,
		MATERIALPREFIX: 'Gold',
	},
	'agapite': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 2,
		MATERIALPREFIX: 'Agapite',
	},
	'verite': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 1,
		MATERIALPREFIX: 'Verite',
	},
	'valorite': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3,
		MATERIALPREFIX: 'Valorite',
	},
	# Leathers
	'leather': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0,
	},
	'spined_leather': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0,
		LUCK: 40,
		MATERIALPREFIX: 'Spined',
	},
	'horned_leather': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 2,
		MATERIALPREFIX: 'Horned',
	},
	'barbed_leather': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4,
		MATERIALPREFIX: 'Barbed',
	},
	# Dragon Scales ( resname2 )
	'red_scales': {
		RESISTANCE_PHYSICAL: 10,
		RESISTANCE_FIRE: -3,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0,
		MATERIALPREFIX: 'Red Scale',
	},
	'yellow_scales': {
		RESISTANCE_PHYSICAL: -3,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0,
		LUCK: 20,
		MATERIALPREFIX: 'Yellow Scale',
	},
	'black_scales': {
		RESISTANCE_PHYSICAL: 10,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: -3,
		MATERIALPREFIX: 'Black Scale',
	},
	'green_scales': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: -3,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 10,
		RESISTANCE_ENERGY: 0,
		MATERIALPREFIX: 'Green Scale',
	},
	'white_scales': {
		RESISTANCE_PHYSICAL: -3,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 10,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0,
		MATERIALPREFIX: 'White Scale',
	},
	'blue_scales': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: -3,
		RESISTANCE_ENERGY: 10,
		MATERIALPREFIX: 'Blue Scale',
	}

}


ARMORINFO = {

	# Bone Armor
	# Chest
	'144f': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	'1454': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	# Arms
	'144e': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	'1453': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	#Gloves
	'1450': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	'1455': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	# Helm
	'1451': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	'1456': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	# Leggings
	'1452': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	'1457': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 4
	},
	# Chain Armor
	# Coif
	'13bb': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 2
	},
	'13c0': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 2
	},
	# Leggings
	'13be': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 2
	},
	'13c3': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 2
	},
	# Tunic
	'13bf': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 2
	},
	'13c4': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 2
	},
	# Platemail
	# Female Plate Armor
	'1c04': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	'1c05': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Helm
	'1412': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	'1419': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Male Armor
	'1415': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	'1416': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Arms
	'1410': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	'1417': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Gloves
	'1414': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	'1418': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Gorget
	'1413': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Leggings
	'1411': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	'141a': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Ringmail
	# Gloves
	'13eb': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	'13f2': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	# Leggings
	'13f0': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	'13f1': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	# Sleeves
	'13ee': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	'13ef': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	# Tunic
	'13ec': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	'13ed': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 3
	},
	# Leather
	# Armor
	'1c06': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'1c07': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Bustier
	'1c0a': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'1c0b': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Cap
	'1db9': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'1dba': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Gloves
	'13c6': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'13ce': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Gorget
	'13c7': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Leggings
	'13cb': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'13d2': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Shorts
	'1c00': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'1c01': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Skirt
	'1c08': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'1c09': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Sleeves
	'13c5': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'13cd': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Tunic
	'13cc': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'13d3': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Studded Leather
	# Armor
	'1c02': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	'1c03': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	# Bustier
	'1c0c': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	'1c0d': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	# Gloves
	'13d5': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	'13dd': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	# Gorget
	'13d6': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	# Leggings
	'13da': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	'13e1': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	# Sleeves
	'13d4': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	'13dc': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	# Tunic
	'13db': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	'13e2': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 4
	},
	# Shields
	# Bronze Shield
	'1b72': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	# Buckler
	'1b73': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 1,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	# Chaos Shield
	'1bc3': {
		RESISTANCE_PHYSICAL: 1,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	# Heater Shield
	'1b76': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	'1b77': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	# Metal Kite Shield
	'1b74': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 1
	},
	'1b75': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 1
	},
	# Metal Shield
	'1b7b': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	# Order Shield
	'1bc4': {
		RESISTANCE_PHYSICAL: 1,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	'1bc5': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 0
	},
	# Wooden Kite Shield
	'1b78': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 1
	},
	'1b79': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 1
	},
	# Wooden Shield
	'1b7a': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 0,
		RESISTANCE_ENERGY: 1
	},
	# Helmets
	# Bascinet
	'140d': {
		RESISTANCE_PHYSICAL: 7,
		RESISTANCE_FIRE: 2,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 2
	},
	'140c': {
		RESISTANCE_PHYSICAL: 7,
		RESISTANCE_FIRE: 2,
		RESISTANCE_COLD: 2,
		RESISTANCE_POISON: 2,
		RESISTANCE_ENERGY: 2
	},
	# Close Helmet
	'1408': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'1409': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Helmet
	'140a': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	'140b': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 4,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 2
	},
	# Nose Helm
	'140e': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 4,
		RESISTANCE_ENERGY: 2
	},
	'140f': {
		RESISTANCE_PHYSICAL: 4,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 4,
		RESISTANCE_POISON: 4,
		RESISTANCE_ENERGY: 2
	},
	# Orc Helm
	'1f0b': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 5
	},
	'1f0c': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 5
	},
	# Hats
	# Bonnet, Feathered Hat, Floppy Hat, Jester Hat, Jesters Cap, Straw Hat, Tricorne Hat, Wide-Brim Hat, Wizards Hat
	'1719': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'171a': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'1713': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'172e': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'171c': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'1717': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'1716': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'171b': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'1714': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	'1718': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 5,
		RESISTANCE_COLD: 9,
		RESISTANCE_POISON: 5,
		RESISTANCE_ENERGY: 5
	},
	# Bandana
	'153f': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 5,
		RESISTANCE_POISON: 8,
		RESISTANCE_ENERGY: 8
	},
	'1540': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 5,
		RESISTANCE_POISON: 8,
		RESISTANCE_ENERGY: 8
	},
	# Skull Cap
	'1543': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 5,
		RESISTANCE_POISON: 8,
		RESISTANCE_ENERGY: 8
	},
	'1544': {
		RESISTANCE_PHYSICAL: 0,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 5,
		RESISTANCE_POISON: 8,
		RESISTANCE_ENERGY: 8
	},
	# Orc Mask
	'141b': {
		RESISTANCE_PHYSICAL: 1,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 7,
		RESISTANCE_POISON: 7,
		RESISTANCE_ENERGY: 8
	},
	'141c': {
		RESISTANCE_PHYSICAL: 1,
		RESISTANCE_FIRE: 1,
		RESISTANCE_COLD: 7,
		RESISTANCE_POISON: 7,
		RESISTANCE_ENERGY: 8
	},
	# Deer Mask
	'1547': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 6,
		RESISTANCE_COLD: 8,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 7
	},
	'1548': {
		RESISTANCE_PHYSICAL: 2,
		RESISTANCE_FIRE: 6,
		RESISTANCE_COLD: 8,
		RESISTANCE_POISON: 1,
		RESISTANCE_ENERGY: 7
	},
	# Bear Mask
	'1545': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 8,
		RESISTANCE_POISON: 4,
		RESISTANCE_ENERGY: 4
	},
	'1546': {
		RESISTANCE_PHYSICAL: 5,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 8,
		RESISTANCE_POISON: 4,
		RESISTANCE_ENERGY: 4
	},
	# Horned Tribal Mask
	'1549': {
		RESISTANCE_PHYSICAL: 6,
		RESISTANCE_FIRE: 9,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 4,
		RESISTANCE_ENERGY: 5
	},
	'154a': {
		RESISTANCE_PHYSICAL: 6,
		RESISTANCE_FIRE: 9,
		RESISTANCE_COLD: 0,
		RESISTANCE_POISON: 4,
		RESISTANCE_ENERGY: 5
	},
	# Red Tribal Mask
	'154b': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 6,
		RESISTANCE_POISON: 10,
		RESISTANCE_ENERGY: 5
	},
	'154c': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 0,
		RESISTANCE_COLD: 6,
		RESISTANCE_POISON: 10,
		RESISTANCE_ENERGY: 5
	},
	# Dragon Scale Armor
	# Sleeves
	'2657': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'2658': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Breastplate
	'2641': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'2642': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Gloves
	'2643': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'2644': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Helm
	'2645': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'2646': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	# Leggings
	'2647': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	},
	'2648': {
		RESISTANCE_PHYSICAL: 3,
		RESISTANCE_FIRE: 3,
		RESISTANCE_COLD: 3,
		RESISTANCE_POISON: 3,
		RESISTANCE_ENERGY: 3
	}
}