######################################################################
# Automatically generated by qmake (1.07a) Sa 25. Dez 14:30:26 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += metatranslator.h proparser.h
SOURCES += fetchtr.cpp \
           fetchtrwp.cpp \
           main.cpp \
           merge.cpp \
           metatranslator.cpp \
           numberh.cpp \
           proparser.cpp \
           sametexth.cpp
